name: Dynamic WORK injection
on:
  push:
    branches:
      - master
  schedule: # Run workflow automatically
    # This will make it run every hour
    - cron: "*/2 * * * 1-5"
    # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
permissions:
  actions: write
  contents: write  # To push a branch 
  pull-requests: write  # To create a PR from that branch
jobs:
  get-office-quotes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Let the magic happen
        uses: actions/setup-node@v3
        with:
          node-version: 14.6.0

      - run: npm i

      - run: node workflow

      - name: Add to git repo
        run: |       
          git config pull.rebase false
          git pull
          git add .
          git config --global user.name "GiovaneRobertiTafine"
          git config --global user.email "kstv23@hotmail.com"
          git commit -m "[Automated] README updated with new Office quote!"
      
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.WORK_TOKEN }}
          repository: geo-smart/curriculum-book-student
          branch: main 
          force: true
