name: Dynamic WORK injection
on:
  push:
    branches:
      - master
  schedule: # Run workflow automatically
    # This will make it run every hour
    - cron: "0 15 1,20 * *"
    # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORK_TOKEN }}
      - name: Let the magic happen
        uses: actions/setup-node@v3
        with:
          node-version: 14.6.0

      - run: npm i

      - run: node workflow

      - name: Add to git repo
        run: | 
          git config pull.rebase false
          git pull
          git add .
          git config --global user.name "GiovaneRobertiTafine"
          git config --global user.email "kstv23@hotmail.com"
          git commit -am "[Automated] WORKFLOW updated with new cron!"
          git push -u origin master
